# Generated by Django 4.1.6 on 2023-02-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_item_description_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
