# Generated by Django 4.1.6 on 2023-02-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_alter_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_price',
            new_name='item_price',
        ),
    ]
