# Generated by Django 4.1.6 on 2023-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_product_id_order_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.FloatField(),
        ),
    ]
